export enum province {
  None = '全国',
  Beijing = '北京',
  Tianjin = '天津',
  Shanghai = '上海',
  Chongqing = '重庆',
  Hebei = '河北',
  Shanxi = '山西',
  InnerMongolia = '内蒙古',
  Liaoning = '辽宁',
  Jilin = '吉林',
  Heilongjiang = '黑龙江',
  Jiangsu = '江苏',
  Zhejiang = '浙江',
  Anhui = '安徽',
  Fujian = '福建',
  Jiangxi = '江西',
  Shandong = '山东',
  Henan = '河南',
  Hubei = '湖北',
  Hunan = '湖南',
  Guangdong = '广东',
  Guangxi = '广西',
  Hainan = '海南',
  Sichuan = '四川',
  Guizhou = '贵州',
  Yunnan = '云南',
  Tibet = '西藏',
  Shaanxi = '陕西',
  Gansu = '甘肃',
  Qinghai = '青海',
  Ningxia = '宁夏',
  Xinjiang = '新疆',
  HongKong = '香港',
  Macau = '澳门',
  Taiwan = '台湾',
}

export enum city {
  None = '',
  Beijing = '北京',
  Tianjin = '天津',
  Shanghai = '上海',
  Guangzhou = '广州',
  Shenzhen = '深圳',
  Nanjing = '南京',
  Suzhou = '苏州',
  Hangzhou = '杭州',
}

export enum rank {
  None=6,
  GDP=1,
  _985=2,
  _211=3,
  DoubleFristClass=4,
  EduFunds=5,
}
