export const gdpData = [
  { name: '北京市', value: '41610.9' },
  { name: '天津市', value: '16311.3' },
  { name: '河北省', value: '42370.4' },
  { name: '山西省', value: '25642.6' },
  { name: '内蒙古自治区', value: '23158.6' },
  { name: '辽宁省', value: '28975.1' },
  { name: '吉林省', value: '13070.2' },
  { name: '黑龙江省', value: '15901.0' },
  { name: '上海市', value: '44652.8' },
  { name: '江苏省', value: '122875.6' },
  { name: '浙江省', value: '77715.4' },
  { name: '安徽省', value: '45045.0' },
  { name: '福建省', value: '53109.9' },
  { name: '江西省', value: '32074.7' },
  { name: '山东省', value: '87435.1' },
  { name: '河南省', value: '61345.1' },
  { name: '湖北省', value: '53734.9' },
  { name: '湖南省', value: '48670.4' },
  { name: '广东省', value: '129118.6' },
  { name: '广西壮族自治区', value: '26300.9' },
  { name: '海南省', value: '6818.2' },
  { name: '重庆市', value: '29129.0' },
  { name: '四川省', value: '56749.8' },
  { name: '贵州省', value: '20164.6' },
  { name: '云南省', value: '28954.2' },
  { name: '西藏自治区', value: '2132.6' },
  { name: '陕西省', value: '32772.7' },
  { name: '甘肃省', value: '11201.6' },
  { name: '青海省', value: '3610.1' },
  { name: '宁夏回族自治区', value: '5069.6' },
  { name: '新疆维吾尔自治区', value: '17741.3' },
]

// 985数组
export const universities985 = [
  { name: '北京市', value: 8 },
  { name: '天津市', value: 2 },
  { name: '河北省', value: 0 },
  { name: '山西省', value: 0 },
  { name: '内蒙古自治区', value: 0 },
  { name: '辽宁省', value: 2 },
  { name: '吉林省', value: 1 },
  { name: '黑龙江省', value: 1 },
  { name: '上海市', value: 4 },
  { name: '江苏省', value: 2 },
  { name: '浙江省', value: 1 },
  { name: '安徽省', value: 1 },
  { name: '福建省', value: 1 },
  { name: '江西省', value: 0 },
  { name: '山东省', value: 2 },
  { name: '河南省', value: 0 },
  { name: '湖北省', value: 2 },
  { name: '湖南省', value: 3 },
  { name: '广东省', value: 2 },
  { name: '广西壮族自治区', value: 0 },
  { name: '海南省', value: 0 },
  { name: '重庆市', value: 1 },
  { name: '四川省', value: 2 },
  { name: '贵州省', value: 0 },
  { name: '云南省', value: 0 },
  { name: '西藏自治区', value: 0 },
  { name: '陕西省', value: 3 },
  { name: '甘肃省', value: 1 },
  { name: '青海省', value: 0 },
  { name: '宁夏回族自治区', value: 0 },
  { name: '新疆维吾尔自治区', value: 0 },
]

// 211数组
export const universities211 = [
  { name: '北京市', value: 27 },
  { name: '天津市', value: 3 },
  { name: '河北省', value: 1 },
  { name: '山西省', value: 1 },
  { name: '内蒙古自治区', value: 1 },
  { name: '辽宁省', value: 4 },
  { name: '吉林省', value: 3 },
  { name: '黑龙江省', value: 4 },
  { name: '上海市', value: 10 },
  { name: '江苏省', value: 11 },
  { name: '浙江省', value: 1 },
  { name: '安徽省', value: 3 },
  { name: '福建省', value: 2 },
  { name: '江西省', value: 1 },
  { name: '山东省', value: 3 },
  { name: '河南省', value: 1 },
  { name: '湖北省', value: 7 },
  { name: '湖南省', value: 4 },
  { name: '广东省', value: 4 },
  { name: '广西壮族自治区', value: 1 },
  { name: '海南省', value: 1 },
  { name: '重庆市', value: 2 },
  { name: '四川省', value: 5 },
  { name: '贵州省', value: 1 },
  { name: '云南省', value: 1 },
  { name: '西藏自治区', value: 1 },
  { name: '陕西省', value: 8 },
  { name: '甘肃省', value: 1 },
  { name: '青海省', value: 1 },
  { name: '宁夏回族自治区', value: 1 },
  { name: '新疆维吾尔自治区', value: 2 },
]

// 双一流数组
export const universitiesDoubleFirstClass = [
  { name: '北京市', value: 11 },
  { name: '天津市', value: 4 },
  { name: '河北省', value: 1 },
  { name: '山西省', value: 1 },
  { name: '内蒙古自治区', value: 1 },
  { name: '辽宁省', value: 3 },
  { name: '吉林省', value: 2 },
  { name: '黑龙江省', value: 2 },
  { name: '上海市', value: 9 },
  { name: '江苏省', value: 6 },
  { name: '浙江省', value: 3 },
  { name: '安徽省', value: 3 },
  { name: '福建省', value: 2 },
  { name: '江西省', value: 1 },
  { name: '山东省', value: 4 },
  { name: '河南省', value: 2 },
  { name: '湖北省', value: 5 },
  { name: '湖南省', value: 5 },
  { name: '广东省', value: 6 },
  { name: '广西壮族自治区', value: 1 },
  { name: '海南省', value: 1 },
  { name: '重庆市', value: 2 },
  { name: '四川省', value: 5 },
  { name: '贵州省', value: 1 },
  { name: '云南省', value: 1 },
  { name: '西藏自治区', value: 1 },
  { name: '陕西省', value: 6 },
  { name: '甘肃省', value: 1 },
  { name: '青海省', value: 1 },
  { name: '宁夏回族自治区', value: 1 },
  { name: '新疆维吾尔自治区', value: 2 },
]

// 教育总经费数组（单位：亿元）
export const educationBudget = [
  { name: '北京市', value: 500 },
  { name: '天津市', value: 200 },
  { name: '河北省', value: 300 },
  { name: '山西省', value: 150 },
  { name: '内蒙古自治区', value: 100 },
  { name: '辽宁省', value: 250 },
  { name: '吉林省', value: 120 },
  { name: '黑龙江省', value: 100 },
  { name: '上海市', value: 400 },
  { name: '江苏省', value: 450 },
  { name: '浙江省', value: 350 },
  { name: '安徽省', value: 200 },
  { name: '福建省', value: 200 },
  { name: '江西省', value: 150 },
  { name: '山东省', value: 400 },
  { name: '河南省', value: 300 },
  { name: '湖北省', value: 250 },
  { name: '湖南省', value: 250 },
  { name: '广东省', value: 600 },
  { name: '广西壮族自治区', value: 150 },
  { name: '海南省', value: 50 },
  { name: '重庆市', value: 200 },
  { name: '四川省', value: 300 },
  { name: '贵州省', value: 100 },
  { name: '云南省', value: 150 },
  { name: '西藏自治区', value: 50 },
  { name: '陕西省', value: 200 },
  { name: '甘肃省', value: 100 },
  { name: '青海省', value: 50 },
  { name: '宁夏回族自治区', value: 50 },
  { name: '新疆维吾尔自治区', value: 150 },
]
